# .github/workflows/deploy.yml

name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Vite app
      - name: Build
        run: npm run build

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload dist folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # Deploy to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
